library(ggplot2)
library(gridExtra)
read_0mRNA = read.table("02.Gene.stat.pl.mRNA.len.txt",header=F)
plot_0mRNA = ggplot(read_0mRNA,aes(V3,col=V1))+geom_density()+xlim(0,100000)+xlab("Gene length (bp)")+ylab("Density")+theme_bw()+theme(legend.position="none")
read_1CDS = read.table("02.Gene.stat.pl.CDS.len.txt",header=F)
plot_1CDS = ggplot(read_1CDS,aes(V3,col=V1))+geom_density()+xlim(0,10000)+xlab("CDS length (bp)")+ylab("Density")+theme_bw()+theme(legend.position="none")
read_2Exon = read.table("02.Gene.stat.pl.Exon.len.txt",header=F)
plot_2Exon = ggplot(read_2Exon,aes(V3,col=V1))+geom_density()+xlim(0,1500)+xlab("Exon length (bp)")+ylab("Density")+theme_bw()+theme(legend.position="none")
read_3Intron = read.table("02.Gene.stat.pl.Intron.len.txt",header=F)
plot_3Intron = ggplot(read_3Intron,aes(V3,col=V1))+geom_density()+xlim(0,10000)+xlab("Intron length (bp)")+ylab("Density")+theme_bw()+theme(legend.position="none")
read_4Exon_num = read.table("02.Gene.stat.pl.Exon.num.txt",header=F)
plot_4Exon_num = ggplot(read_4Exon_num,aes(V3,col=V1))+geom_density()+xlim(0,50)+xlab("Exon number")+ylab("Density")+theme_bw()+theme(legend.position="none")
plot_legend_4Exon_num = ggplot(read_4Exon_num,aes(V3,col=V1))+geom_density()+xlim(0,50)+xlab("Exon number")+ylab("Density")+theme_bw()
pdf(file="03.plot.pl.pdf",width=8,height=10)
grid.arrange(plot_0mRNA,plot_1CDS,plot_2Exon,plot_3Intron,plot_4Exon_num,plot_legend_4Exon_num,ncol=2)
dev.off()
