/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_1.hap --map chr/scaffold_1.map --out ihs/scaffold_1.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_10.hap --map chr/scaffold_10.map --out ihs/scaffold_10.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_101.hap --map chr/scaffold_101.map --out ihs/scaffold_101.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_103.hap --map chr/scaffold_103.map --out ihs/scaffold_103.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_105.hap --map chr/scaffold_105.map --out ihs/scaffold_105.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_106.hap --map chr/scaffold_106.map --out ihs/scaffold_106.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_107.hap --map chr/scaffold_107.map --out ihs/scaffold_107.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_109.hap --map chr/scaffold_109.map --out ihs/scaffold_109.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_11.hap --map chr/scaffold_11.map --out ihs/scaffold_11.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_110.hap --map chr/scaffold_110.map --out ihs/scaffold_110.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_113.hap --map chr/scaffold_113.map --out ihs/scaffold_113.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_114.hap --map chr/scaffold_114.map --out ihs/scaffold_114.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_119.hap --map chr/scaffold_119.map --out ihs/scaffold_119.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_12.hap --map chr/scaffold_12.map --out ihs/scaffold_12.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_120.hap --map chr/scaffold_120.map --out ihs/scaffold_120.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_121.hap --map chr/scaffold_121.map --out ihs/scaffold_121.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_124.hap --map chr/scaffold_124.map --out ihs/scaffold_124.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_125.hap --map chr/scaffold_125.map --out ihs/scaffold_125.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_126.hap --map chr/scaffold_126.map --out ihs/scaffold_126.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_127.hap --map chr/scaffold_127.map --out ihs/scaffold_127.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_128.hap --map chr/scaffold_128.map --out ihs/scaffold_128.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_129.hap --map chr/scaffold_129.map --out ihs/scaffold_129.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_13.hap --map chr/scaffold_13.map --out ihs/scaffold_13.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_130.hap --map chr/scaffold_130.map --out ihs/scaffold_130.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_131.hap --map chr/scaffold_131.map --out ihs/scaffold_131.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_132.hap --map chr/scaffold_132.map --out ihs/scaffold_132.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_133.hap --map chr/scaffold_133.map --out ihs/scaffold_133.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_134.hap --map chr/scaffold_134.map --out ihs/scaffold_134.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_136.hap --map chr/scaffold_136.map --out ihs/scaffold_136.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_139.hap --map chr/scaffold_139.map --out ihs/scaffold_139.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_14.hap --map chr/scaffold_14.map --out ihs/scaffold_14.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_140.hap --map chr/scaffold_140.map --out ihs/scaffold_140.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_142.hap --map chr/scaffold_142.map --out ihs/scaffold_142.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_143.hap --map chr/scaffold_143.map --out ihs/scaffold_143.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_144.hap --map chr/scaffold_144.map --out ihs/scaffold_144.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_145.hap --map chr/scaffold_145.map --out ihs/scaffold_145.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_147.hap --map chr/scaffold_147.map --out ihs/scaffold_147.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_148.hap --map chr/scaffold_148.map --out ihs/scaffold_148.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_149.hap --map chr/scaffold_149.map --out ihs/scaffold_149.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_15.hap --map chr/scaffold_15.map --out ihs/scaffold_15.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_150.hap --map chr/scaffold_150.map --out ihs/scaffold_150.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_151.hap --map chr/scaffold_151.map --out ihs/scaffold_151.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_152.hap --map chr/scaffold_152.map --out ihs/scaffold_152.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_153.hap --map chr/scaffold_153.map --out ihs/scaffold_153.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_155.hap --map chr/scaffold_155.map --out ihs/scaffold_155.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_157.hap --map chr/scaffold_157.map --out ihs/scaffold_157.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_159.hap --map chr/scaffold_159.map --out ihs/scaffold_159.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_16.hap --map chr/scaffold_16.map --out ihs/scaffold_16.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_160.hap --map chr/scaffold_160.map --out ihs/scaffold_160.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_162.hap --map chr/scaffold_162.map --out ihs/scaffold_162.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_164.hap --map chr/scaffold_164.map --out ihs/scaffold_164.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_166.hap --map chr/scaffold_166.map --out ihs/scaffold_166.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_168.hap --map chr/scaffold_168.map --out ihs/scaffold_168.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_17.hap --map chr/scaffold_17.map --out ihs/scaffold_17.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_171.hap --map chr/scaffold_171.map --out ihs/scaffold_171.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_172.hap --map chr/scaffold_172.map --out ihs/scaffold_172.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_174.hap --map chr/scaffold_174.map --out ihs/scaffold_174.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_178.hap --map chr/scaffold_178.map --out ihs/scaffold_178.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_18.hap --map chr/scaffold_18.map --out ihs/scaffold_18.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_183.hap --map chr/scaffold_183.map --out ihs/scaffold_183.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_184.hap --map chr/scaffold_184.map --out ihs/scaffold_184.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_185.hap --map chr/scaffold_185.map --out ihs/scaffold_185.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_186.hap --map chr/scaffold_186.map --out ihs/scaffold_186.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_187.hap --map chr/scaffold_187.map --out ihs/scaffold_187.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_19.hap --map chr/scaffold_19.map --out ihs/scaffold_19.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_191.hap --map chr/scaffold_191.map --out ihs/scaffold_191.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_192.hap --map chr/scaffold_192.map --out ihs/scaffold_192.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_194.hap --map chr/scaffold_194.map --out ihs/scaffold_194.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_195.hap --map chr/scaffold_195.map --out ihs/scaffold_195.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_197.hap --map chr/scaffold_197.map --out ihs/scaffold_197.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_198.hap --map chr/scaffold_198.map --out ihs/scaffold_198.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_2.hap --map chr/scaffold_2.map --out ihs/scaffold_2.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_20.hap --map chr/scaffold_20.map --out ihs/scaffold_20.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_201.hap --map chr/scaffold_201.map --out ihs/scaffold_201.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_204.hap --map chr/scaffold_204.map --out ihs/scaffold_204.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_205.hap --map chr/scaffold_205.map --out ihs/scaffold_205.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_206.hap --map chr/scaffold_206.map --out ihs/scaffold_206.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_208.hap --map chr/scaffold_208.map --out ihs/scaffold_208.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_21.hap --map chr/scaffold_21.map --out ihs/scaffold_21.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_210.hap --map chr/scaffold_210.map --out ihs/scaffold_210.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_211.hap --map chr/scaffold_211.map --out ihs/scaffold_211.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_212.hap --map chr/scaffold_212.map --out ihs/scaffold_212.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_213.hap --map chr/scaffold_213.map --out ihs/scaffold_213.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_214.hap --map chr/scaffold_214.map --out ihs/scaffold_214.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_215.hap --map chr/scaffold_215.map --out ihs/scaffold_215.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_216.hap --map chr/scaffold_216.map --out ihs/scaffold_216.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_218.hap --map chr/scaffold_218.map --out ihs/scaffold_218.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_22.hap --map chr/scaffold_22.map --out ihs/scaffold_22.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_222.hap --map chr/scaffold_222.map --out ihs/scaffold_222.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_224.hap --map chr/scaffold_224.map --out ihs/scaffold_224.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_225.hap --map chr/scaffold_225.map --out ihs/scaffold_225.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_226.hap --map chr/scaffold_226.map --out ihs/scaffold_226.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_229.hap --map chr/scaffold_229.map --out ihs/scaffold_229.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_23.hap --map chr/scaffold_23.map --out ihs/scaffold_23.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_231.hap --map chr/scaffold_231.map --out ihs/scaffold_231.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_233.hap --map chr/scaffold_233.map --out ihs/scaffold_233.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_234.hap --map chr/scaffold_234.map --out ihs/scaffold_234.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_24.hap --map chr/scaffold_24.map --out ihs/scaffold_24.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_240.hap --map chr/scaffold_240.map --out ihs/scaffold_240.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_242.hap --map chr/scaffold_242.map --out ihs/scaffold_242.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_243.hap --map chr/scaffold_243.map --out ihs/scaffold_243.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_246.hap --map chr/scaffold_246.map --out ihs/scaffold_246.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_247.hap --map chr/scaffold_247.map --out ihs/scaffold_247.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_248.hap --map chr/scaffold_248.map --out ihs/scaffold_248.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_249.hap --map chr/scaffold_249.map --out ihs/scaffold_249.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_25.hap --map chr/scaffold_25.map --out ihs/scaffold_25.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_257.hap --map chr/scaffold_257.map --out ihs/scaffold_257.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_26.hap --map chr/scaffold_26.map --out ihs/scaffold_26.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_262.hap --map chr/scaffold_262.map --out ihs/scaffold_262.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_264.hap --map chr/scaffold_264.map --out ihs/scaffold_264.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_265.hap --map chr/scaffold_265.map --out ihs/scaffold_265.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_269.hap --map chr/scaffold_269.map --out ihs/scaffold_269.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_271.hap --map chr/scaffold_271.map --out ihs/scaffold_271.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_273.hap --map chr/scaffold_273.map --out ihs/scaffold_273.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_274.hap --map chr/scaffold_274.map --out ihs/scaffold_274.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_275.hap --map chr/scaffold_275.map --out ihs/scaffold_275.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_278.hap --map chr/scaffold_278.map --out ihs/scaffold_278.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_28.hap --map chr/scaffold_28.map --out ihs/scaffold_28.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_282.hap --map chr/scaffold_282.map --out ihs/scaffold_282.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_283.hap --map chr/scaffold_283.map --out ihs/scaffold_283.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_284.hap --map chr/scaffold_284.map --out ihs/scaffold_284.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_285.hap --map chr/scaffold_285.map --out ihs/scaffold_285.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_286.hap --map chr/scaffold_286.map --out ihs/scaffold_286.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_287.hap --map chr/scaffold_287.map --out ihs/scaffold_287.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_292.hap --map chr/scaffold_292.map --out ihs/scaffold_292.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_295.hap --map chr/scaffold_295.map --out ihs/scaffold_295.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_296.hap --map chr/scaffold_296.map --out ihs/scaffold_296.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_297.hap --map chr/scaffold_297.map --out ihs/scaffold_297.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_298.hap --map chr/scaffold_298.map --out ihs/scaffold_298.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_299.hap --map chr/scaffold_299.map --out ihs/scaffold_299.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_3.hap --map chr/scaffold_3.map --out ihs/scaffold_3.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_30.hap --map chr/scaffold_30.map --out ihs/scaffold_30.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_300.hap --map chr/scaffold_300.map --out ihs/scaffold_300.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_303.hap --map chr/scaffold_303.map --out ihs/scaffold_303.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_308.hap --map chr/scaffold_308.map --out ihs/scaffold_308.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_31.hap --map chr/scaffold_31.map --out ihs/scaffold_31.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_313.hap --map chr/scaffold_313.map --out ihs/scaffold_313.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_314.hap --map chr/scaffold_314.map --out ihs/scaffold_314.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_315.hap --map chr/scaffold_315.map --out ihs/scaffold_315.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_316.hap --map chr/scaffold_316.map --out ihs/scaffold_316.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_319.hap --map chr/scaffold_319.map --out ihs/scaffold_319.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_32.hap --map chr/scaffold_32.map --out ihs/scaffold_32.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_320.hap --map chr/scaffold_320.map --out ihs/scaffold_320.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_321.hap --map chr/scaffold_321.map --out ihs/scaffold_321.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_322.hap --map chr/scaffold_322.map --out ihs/scaffold_322.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_324.hap --map chr/scaffold_324.map --out ihs/scaffold_324.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_328.hap --map chr/scaffold_328.map --out ihs/scaffold_328.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_330.hap --map chr/scaffold_330.map --out ihs/scaffold_330.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_332.hap --map chr/scaffold_332.map --out ihs/scaffold_332.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_333.hap --map chr/scaffold_333.map --out ihs/scaffold_333.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_337.hap --map chr/scaffold_337.map --out ihs/scaffold_337.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_338.hap --map chr/scaffold_338.map --out ihs/scaffold_338.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_339.hap --map chr/scaffold_339.map --out ihs/scaffold_339.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_342.hap --map chr/scaffold_342.map --out ihs/scaffold_342.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_348.hap --map chr/scaffold_348.map --out ihs/scaffold_348.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_35.hap --map chr/scaffold_35.map --out ihs/scaffold_35.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_353.hap --map chr/scaffold_353.map --out ihs/scaffold_353.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_355.hap --map chr/scaffold_355.map --out ihs/scaffold_355.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_360.hap --map chr/scaffold_360.map --out ihs/scaffold_360.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_361.hap --map chr/scaffold_361.map --out ihs/scaffold_361.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_364.hap --map chr/scaffold_364.map --out ihs/scaffold_364.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_369.hap --map chr/scaffold_369.map --out ihs/scaffold_369.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_370.hap --map chr/scaffold_370.map --out ihs/scaffold_370.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_371.hap --map chr/scaffold_371.map --out ihs/scaffold_371.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_375.hap --map chr/scaffold_375.map --out ihs/scaffold_375.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_378.hap --map chr/scaffold_378.map --out ihs/scaffold_378.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_380.hap --map chr/scaffold_380.map --out ihs/scaffold_380.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_381.hap --map chr/scaffold_381.map --out ihs/scaffold_381.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_382.hap --map chr/scaffold_382.map --out ihs/scaffold_382.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_387.hap --map chr/scaffold_387.map --out ihs/scaffold_387.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_388.hap --map chr/scaffold_388.map --out ihs/scaffold_388.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_389.hap --map chr/scaffold_389.map --out ihs/scaffold_389.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_39.hap --map chr/scaffold_39.map --out ihs/scaffold_39.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_391.hap --map chr/scaffold_391.map --out ihs/scaffold_391.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_392.hap --map chr/scaffold_392.map --out ihs/scaffold_392.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_393.hap --map chr/scaffold_393.map --out ihs/scaffold_393.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_395.hap --map chr/scaffold_395.map --out ihs/scaffold_395.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_396.hap --map chr/scaffold_396.map --out ihs/scaffold_396.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_397.hap --map chr/scaffold_397.map --out ihs/scaffold_397.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_4.hap --map chr/scaffold_4.map --out ihs/scaffold_4.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_40.hap --map chr/scaffold_40.map --out ihs/scaffold_40.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_400.hap --map chr/scaffold_400.map --out ihs/scaffold_400.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_41.hap --map chr/scaffold_41.map --out ihs/scaffold_41.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_410.hap --map chr/scaffold_410.map --out ihs/scaffold_410.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_411.hap --map chr/scaffold_411.map --out ihs/scaffold_411.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_412.hap --map chr/scaffold_412.map --out ihs/scaffold_412.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_413.hap --map chr/scaffold_413.map --out ihs/scaffold_413.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_415.hap --map chr/scaffold_415.map --out ihs/scaffold_415.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_416.hap --map chr/scaffold_416.map --out ihs/scaffold_416.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_417.hap --map chr/scaffold_417.map --out ihs/scaffold_417.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_418.hap --map chr/scaffold_418.map --out ihs/scaffold_418.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_421.hap --map chr/scaffold_421.map --out ihs/scaffold_421.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_424.hap --map chr/scaffold_424.map --out ihs/scaffold_424.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_425.hap --map chr/scaffold_425.map --out ihs/scaffold_425.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_433.hap --map chr/scaffold_433.map --out ihs/scaffold_433.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_434.hap --map chr/scaffold_434.map --out ihs/scaffold_434.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_44.hap --map chr/scaffold_44.map --out ihs/scaffold_44.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_442.hap --map chr/scaffold_442.map --out ihs/scaffold_442.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_444.hap --map chr/scaffold_444.map --out ihs/scaffold_444.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_445.hap --map chr/scaffold_445.map --out ihs/scaffold_445.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_448.hap --map chr/scaffold_448.map --out ihs/scaffold_448.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_449.hap --map chr/scaffold_449.map --out ihs/scaffold_449.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_450.hap --map chr/scaffold_450.map --out ihs/scaffold_450.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_451.hap --map chr/scaffold_451.map --out ihs/scaffold_451.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_452.hap --map chr/scaffold_452.map --out ihs/scaffold_452.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_454.hap --map chr/scaffold_454.map --out ihs/scaffold_454.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_456.hap --map chr/scaffold_456.map --out ihs/scaffold_456.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_459.hap --map chr/scaffold_459.map --out ihs/scaffold_459.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_46.hap --map chr/scaffold_46.map --out ihs/scaffold_46.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_460.hap --map chr/scaffold_460.map --out ihs/scaffold_460.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_461.hap --map chr/scaffold_461.map --out ihs/scaffold_461.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_463.hap --map chr/scaffold_463.map --out ihs/scaffold_463.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_464.hap --map chr/scaffold_464.map --out ihs/scaffold_464.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_467.hap --map chr/scaffold_467.map --out ihs/scaffold_467.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_468.hap --map chr/scaffold_468.map --out ihs/scaffold_468.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_471.hap --map chr/scaffold_471.map --out ihs/scaffold_471.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_473.hap --map chr/scaffold_473.map --out ihs/scaffold_473.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_478.hap --map chr/scaffold_478.map --out ihs/scaffold_478.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_479.hap --map chr/scaffold_479.map --out ihs/scaffold_479.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_48.hap --map chr/scaffold_48.map --out ihs/scaffold_48.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_481.hap --map chr/scaffold_481.map --out ihs/scaffold_481.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_482.hap --map chr/scaffold_482.map --out ihs/scaffold_482.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_483.hap --map chr/scaffold_483.map --out ihs/scaffold_483.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_484.hap --map chr/scaffold_484.map --out ihs/scaffold_484.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_486.hap --map chr/scaffold_486.map --out ihs/scaffold_486.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_488.hap --map chr/scaffold_488.map --out ihs/scaffold_488.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_49.hap --map chr/scaffold_49.map --out ihs/scaffold_49.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_491.hap --map chr/scaffold_491.map --out ihs/scaffold_491.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_492.hap --map chr/scaffold_492.map --out ihs/scaffold_492.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_493.hap --map chr/scaffold_493.map --out ihs/scaffold_493.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_494.hap --map chr/scaffold_494.map --out ihs/scaffold_494.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_495.hap --map chr/scaffold_495.map --out ihs/scaffold_495.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_499.hap --map chr/scaffold_499.map --out ihs/scaffold_499.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_5.hap --map chr/scaffold_5.map --out ihs/scaffold_5.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_50.hap --map chr/scaffold_50.map --out ihs/scaffold_50.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_503.hap --map chr/scaffold_503.map --out ihs/scaffold_503.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_509.hap --map chr/scaffold_509.map --out ihs/scaffold_509.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_510.hap --map chr/scaffold_510.map --out ihs/scaffold_510.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_511.hap --map chr/scaffold_511.map --out ihs/scaffold_511.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_512.hap --map chr/scaffold_512.map --out ihs/scaffold_512.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_513.hap --map chr/scaffold_513.map --out ihs/scaffold_513.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_514.hap --map chr/scaffold_514.map --out ihs/scaffold_514.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_52.hap --map chr/scaffold_52.map --out ihs/scaffold_52.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_520.hap --map chr/scaffold_520.map --out ihs/scaffold_520.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_521.hap --map chr/scaffold_521.map --out ihs/scaffold_521.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_525.hap --map chr/scaffold_525.map --out ihs/scaffold_525.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_53.hap --map chr/scaffold_53.map --out ihs/scaffold_53.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_531.hap --map chr/scaffold_531.map --out ihs/scaffold_531.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_535.hap --map chr/scaffold_535.map --out ihs/scaffold_535.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_536.hap --map chr/scaffold_536.map --out ihs/scaffold_536.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_538.hap --map chr/scaffold_538.map --out ihs/scaffold_538.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_539.hap --map chr/scaffold_539.map --out ihs/scaffold_539.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_54.hap --map chr/scaffold_54.map --out ihs/scaffold_54.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_542.hap --map chr/scaffold_542.map --out ihs/scaffold_542.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_543.hap --map chr/scaffold_543.map --out ihs/scaffold_543.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_545.hap --map chr/scaffold_545.map --out ihs/scaffold_545.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_546.hap --map chr/scaffold_546.map --out ihs/scaffold_546.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_549.hap --map chr/scaffold_549.map --out ihs/scaffold_549.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_550.hap --map chr/scaffold_550.map --out ihs/scaffold_550.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_568.hap --map chr/scaffold_568.map --out ihs/scaffold_568.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_57.hap --map chr/scaffold_57.map --out ihs/scaffold_57.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_570.hap --map chr/scaffold_570.map --out ihs/scaffold_570.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_571.hap --map chr/scaffold_571.map --out ihs/scaffold_571.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_577.hap --map chr/scaffold_577.map --out ihs/scaffold_577.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_578.hap --map chr/scaffold_578.map --out ihs/scaffold_578.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_579.hap --map chr/scaffold_579.map --out ihs/scaffold_579.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_58.hap --map chr/scaffold_58.map --out ihs/scaffold_58.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_581.hap --map chr/scaffold_581.map --out ihs/scaffold_581.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_582.hap --map chr/scaffold_582.map --out ihs/scaffold_582.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_583.hap --map chr/scaffold_583.map --out ihs/scaffold_583.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_584.hap --map chr/scaffold_584.map --out ihs/scaffold_584.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_585.hap --map chr/scaffold_585.map --out ihs/scaffold_585.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_586.hap --map chr/scaffold_586.map --out ihs/scaffold_586.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_588.hap --map chr/scaffold_588.map --out ihs/scaffold_588.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_589.hap --map chr/scaffold_589.map --out ihs/scaffold_589.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_59.hap --map chr/scaffold_59.map --out ihs/scaffold_59.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_590.hap --map chr/scaffold_590.map --out ihs/scaffold_590.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_594.hap --map chr/scaffold_594.map --out ihs/scaffold_594.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_598.hap --map chr/scaffold_598.map --out ihs/scaffold_598.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_599.hap --map chr/scaffold_599.map --out ihs/scaffold_599.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_6.hap --map chr/scaffold_6.map --out ihs/scaffold_6.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_601.hap --map chr/scaffold_601.map --out ihs/scaffold_601.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_606.hap --map chr/scaffold_606.map --out ihs/scaffold_606.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_607.hap --map chr/scaffold_607.map --out ihs/scaffold_607.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_61.hap --map chr/scaffold_61.map --out ihs/scaffold_61.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_615.hap --map chr/scaffold_615.map --out ihs/scaffold_615.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_616.hap --map chr/scaffold_616.map --out ihs/scaffold_616.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_62.hap --map chr/scaffold_62.map --out ihs/scaffold_62.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_620.hap --map chr/scaffold_620.map --out ihs/scaffold_620.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_624.hap --map chr/scaffold_624.map --out ihs/scaffold_624.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_63.hap --map chr/scaffold_63.map --out ihs/scaffold_63.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_636.hap --map chr/scaffold_636.map --out ihs/scaffold_636.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_637.hap --map chr/scaffold_637.map --out ihs/scaffold_637.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_639.hap --map chr/scaffold_639.map --out ihs/scaffold_639.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_64.hap --map chr/scaffold_64.map --out ihs/scaffold_64.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_643.hap --map chr/scaffold_643.map --out ihs/scaffold_643.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_645.hap --map chr/scaffold_645.map --out ihs/scaffold_645.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_646.hap --map chr/scaffold_646.map --out ihs/scaffold_646.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_647.hap --map chr/scaffold_647.map --out ihs/scaffold_647.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_65.hap --map chr/scaffold_65.map --out ihs/scaffold_65.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_651.hap --map chr/scaffold_651.map --out ihs/scaffold_651.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_653.hap --map chr/scaffold_653.map --out ihs/scaffold_653.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_655.hap --map chr/scaffold_655.map --out ihs/scaffold_655.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_656.hap --map chr/scaffold_656.map --out ihs/scaffold_656.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_657.hap --map chr/scaffold_657.map --out ihs/scaffold_657.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_658.hap --map chr/scaffold_658.map --out ihs/scaffold_658.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_659.hap --map chr/scaffold_659.map --out ihs/scaffold_659.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_66.hap --map chr/scaffold_66.map --out ihs/scaffold_66.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_664.hap --map chr/scaffold_664.map --out ihs/scaffold_664.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_666.hap --map chr/scaffold_666.map --out ihs/scaffold_666.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_67.hap --map chr/scaffold_67.map --out ihs/scaffold_67.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_670.hap --map chr/scaffold_670.map --out ihs/scaffold_670.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_671.hap --map chr/scaffold_671.map --out ihs/scaffold_671.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_674.hap --map chr/scaffold_674.map --out ihs/scaffold_674.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_677.hap --map chr/scaffold_677.map --out ihs/scaffold_677.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_679.hap --map chr/scaffold_679.map --out ihs/scaffold_679.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_680.hap --map chr/scaffold_680.map --out ihs/scaffold_680.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_682.hap --map chr/scaffold_682.map --out ihs/scaffold_682.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_683.hap --map chr/scaffold_683.map --out ihs/scaffold_683.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_692.hap --map chr/scaffold_692.map --out ihs/scaffold_692.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_698.hap --map chr/scaffold_698.map --out ihs/scaffold_698.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_699.hap --map chr/scaffold_699.map --out ihs/scaffold_699.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_7.hap --map chr/scaffold_7.map --out ihs/scaffold_7.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_701.hap --map chr/scaffold_701.map --out ihs/scaffold_701.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_703.hap --map chr/scaffold_703.map --out ihs/scaffold_703.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_704.hap --map chr/scaffold_704.map --out ihs/scaffold_704.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_706.hap --map chr/scaffold_706.map --out ihs/scaffold_706.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_707.hap --map chr/scaffold_707.map --out ihs/scaffold_707.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_712.hap --map chr/scaffold_712.map --out ihs/scaffold_712.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_713.hap --map chr/scaffold_713.map --out ihs/scaffold_713.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_714.hap --map chr/scaffold_714.map --out ihs/scaffold_714.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_72.hap --map chr/scaffold_72.map --out ihs/scaffold_72.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_723.hap --map chr/scaffold_723.map --out ihs/scaffold_723.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_725.hap --map chr/scaffold_725.map --out ihs/scaffold_725.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_727.hap --map chr/scaffold_727.map --out ihs/scaffold_727.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_73.hap --map chr/scaffold_73.map --out ihs/scaffold_73.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_731.hap --map chr/scaffold_731.map --out ihs/scaffold_731.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_732.hap --map chr/scaffold_732.map --out ihs/scaffold_732.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_733.hap --map chr/scaffold_733.map --out ihs/scaffold_733.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_736.hap --map chr/scaffold_736.map --out ihs/scaffold_736.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_739.hap --map chr/scaffold_739.map --out ihs/scaffold_739.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_74.hap --map chr/scaffold_74.map --out ihs/scaffold_74.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_741.hap --map chr/scaffold_741.map --out ihs/scaffold_741.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_742.hap --map chr/scaffold_742.map --out ihs/scaffold_742.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_744.hap --map chr/scaffold_744.map --out ihs/scaffold_744.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_747.hap --map chr/scaffold_747.map --out ihs/scaffold_747.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_750.hap --map chr/scaffold_750.map --out ihs/scaffold_750.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_753.hap --map chr/scaffold_753.map --out ihs/scaffold_753.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_756.hap --map chr/scaffold_756.map --out ihs/scaffold_756.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_757.hap --map chr/scaffold_757.map --out ihs/scaffold_757.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_759.hap --map chr/scaffold_759.map --out ihs/scaffold_759.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_76.hap --map chr/scaffold_76.map --out ihs/scaffold_76.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_760.hap --map chr/scaffold_760.map --out ihs/scaffold_760.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_763.hap --map chr/scaffold_763.map --out ihs/scaffold_763.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_764.hap --map chr/scaffold_764.map --out ihs/scaffold_764.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_766.hap --map chr/scaffold_766.map --out ihs/scaffold_766.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_767.hap --map chr/scaffold_767.map --out ihs/scaffold_767.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_769.hap --map chr/scaffold_769.map --out ihs/scaffold_769.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_77.hap --map chr/scaffold_77.map --out ihs/scaffold_77.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_773.hap --map chr/scaffold_773.map --out ihs/scaffold_773.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_775.hap --map chr/scaffold_775.map --out ihs/scaffold_775.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_777.hap --map chr/scaffold_777.map --out ihs/scaffold_777.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_779.hap --map chr/scaffold_779.map --out ihs/scaffold_779.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_78.hap --map chr/scaffold_78.map --out ihs/scaffold_78.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_780.hap --map chr/scaffold_780.map --out ihs/scaffold_780.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_785.hap --map chr/scaffold_785.map --out ihs/scaffold_785.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_786.hap --map chr/scaffold_786.map --out ihs/scaffold_786.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_788.hap --map chr/scaffold_788.map --out ihs/scaffold_788.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_790.hap --map chr/scaffold_790.map --out ihs/scaffold_790.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_792.hap --map chr/scaffold_792.map --out ihs/scaffold_792.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_798.hap --map chr/scaffold_798.map --out ihs/scaffold_798.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_8.hap --map chr/scaffold_8.map --out ihs/scaffold_8.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_80.hap --map chr/scaffold_80.map --out ihs/scaffold_80.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_800.hap --map chr/scaffold_800.map --out ihs/scaffold_800.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_804.hap --map chr/scaffold_804.map --out ihs/scaffold_804.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_807.hap --map chr/scaffold_807.map --out ihs/scaffold_807.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_813.hap --map chr/scaffold_813.map --out ihs/scaffold_813.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_82.hap --map chr/scaffold_82.map --out ihs/scaffold_82.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_820.hap --map chr/scaffold_820.map --out ihs/scaffold_820.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_821.hap --map chr/scaffold_821.map --out ihs/scaffold_821.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_822.hap --map chr/scaffold_822.map --out ihs/scaffold_822.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_824.hap --map chr/scaffold_824.map --out ihs/scaffold_824.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_827.hap --map chr/scaffold_827.map --out ihs/scaffold_827.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_83.hap --map chr/scaffold_83.map --out ihs/scaffold_83.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_835.hap --map chr/scaffold_835.map --out ihs/scaffold_835.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_836.hap --map chr/scaffold_836.map --out ihs/scaffold_836.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_837.hap --map chr/scaffold_837.map --out ihs/scaffold_837.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_845.hap --map chr/scaffold_845.map --out ihs/scaffold_845.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_847.hap --map chr/scaffold_847.map --out ihs/scaffold_847.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_848.hap --map chr/scaffold_848.map --out ihs/scaffold_848.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_85.hap --map chr/scaffold_85.map --out ihs/scaffold_85.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_855.hap --map chr/scaffold_855.map --out ihs/scaffold_855.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_856.hap --map chr/scaffold_856.map --out ihs/scaffold_856.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_857.hap --map chr/scaffold_857.map --out ihs/scaffold_857.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_859.hap --map chr/scaffold_859.map --out ihs/scaffold_859.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_862.hap --map chr/scaffold_862.map --out ihs/scaffold_862.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_868.hap --map chr/scaffold_868.map --out ihs/scaffold_868.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_870.hap --map chr/scaffold_870.map --out ihs/scaffold_870.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_871.hap --map chr/scaffold_871.map --out ihs/scaffold_871.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_875.hap --map chr/scaffold_875.map --out ihs/scaffold_875.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_879.hap --map chr/scaffold_879.map --out ihs/scaffold_879.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_884.hap --map chr/scaffold_884.map --out ihs/scaffold_884.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_885.hap --map chr/scaffold_885.map --out ihs/scaffold_885.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_886.hap --map chr/scaffold_886.map --out ihs/scaffold_886.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_887.hap --map chr/scaffold_887.map --out ihs/scaffold_887.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_894.hap --map chr/scaffold_894.map --out ihs/scaffold_894.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_896.hap --map chr/scaffold_896.map --out ihs/scaffold_896.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_899.hap --map chr/scaffold_899.map --out ihs/scaffold_899.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_9.hap --map chr/scaffold_9.map --out ihs/scaffold_9.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_90.hap --map chr/scaffold_90.map --out ihs/scaffold_90.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_904.hap --map chr/scaffold_904.map --out ihs/scaffold_904.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_906.hap --map chr/scaffold_906.map --out ihs/scaffold_906.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_918.hap --map chr/scaffold_918.map --out ihs/scaffold_918.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_919.hap --map chr/scaffold_919.map --out ihs/scaffold_919.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_92.hap --map chr/scaffold_92.map --out ihs/scaffold_92.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_923.hap --map chr/scaffold_923.map --out ihs/scaffold_923.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_924.hap --map chr/scaffold_924.map --out ihs/scaffold_924.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_926.hap --map chr/scaffold_926.map --out ihs/scaffold_926.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_927.hap --map chr/scaffold_927.map --out ihs/scaffold_927.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_929.hap --map chr/scaffold_929.map --out ihs/scaffold_929.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_930.hap --map chr/scaffold_930.map --out ihs/scaffold_930.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_931.hap --map chr/scaffold_931.map --out ihs/scaffold_931.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_94.hap --map chr/scaffold_94.map --out ihs/scaffold_94.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_940.hap --map chr/scaffold_940.map --out ihs/scaffold_940.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_942.hap --map chr/scaffold_942.map --out ihs/scaffold_942.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_95.hap --map chr/scaffold_95.map --out ihs/scaffold_95.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_952.hap --map chr/scaffold_952.map --out ihs/scaffold_952.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_958.hap --map chr/scaffold_958.map --out ihs/scaffold_958.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_96.hap --map chr/scaffold_96.map --out ihs/scaffold_96.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_966.hap --map chr/scaffold_966.map --out ihs/scaffold_966.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_969.hap --map chr/scaffold_969.map --out ihs/scaffold_969.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_97.hap --map chr/scaffold_97.map --out ihs/scaffold_97.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_973.hap --map chr/scaffold_973.map --out ihs/scaffold_973.txt
/home/share/user/user101/software/selscan/selscan/bin/linux/selscan --ihs --hap chr/scaffold_98.hap --map chr/scaffold_98.map --out ihs/scaffold_98.txt
